---
# tasks file for r-app-01



  - name: Enable repository jboss EAP 
    rhsm_repository:
        name: jb-eap-7-for-rhel-7-server-rpms

  - name: Instala server application 
    yum:
      name: "@jboss-eap7"
      state: present 

  - name: Start manual jboss 
    shell: "/opt/rh/eap7/root/usr/share/wildfly/bin/standalone.sh"
    register: _result
       
  - name: Debug 
    debug: 
      msg: 
       - Saida dos servicos desabilitados  '{{ _result }}' 
  
    

     